events {}

http {

    upstream restaurant_service {
        server restaurant-service:3001;
    }

    upstream menu_service {
        server menu-service:3002;
    }

    upstream order_service {
        server order-service:3003;
    }

    server {
        listen 8080;

        
        location /restaurants {
            proxy_set_header X-Correlation-ID $request_id;
            proxy_pass http://restaurant_service;
        }

        location /menus {
            proxy_set_header X-Correlation-ID $request_id;
            proxy_pass http://menu_service;
        }

        location /orders {
            proxy_set_header X-Correlation-ID $request_id;
            proxy_pass http://order_service;
        }

        location /gateway/health {
            return 200 '{"status":"UP","gateway":"nginx"}';
            add_header Content-Type application/json;
        }

       
    }
}